@startuml
actor AppUser

AppUser -> Monitoring: Share Information
activate Monitoring
create Sharing
Monitoring -> Sharing: <<create>>
deactivate Monitoring
activate Sharing
Sharing -> Sharing: Read Information
activate Sharing
Sharing <-- Sharing
deactivate Sharing
AppUser <-- Sharing: Ready
deactivate Sharing

actor DoctorPhone
AppUser -> Sharing: Send SMS
activate Sharing
Sharing -> DoctorPhone: SMS Message
alt success
Sharing <-- DoctorPhone: Received
AppUser <-- Sharing: SMS Message Sent Successfully
else failure
Sharing <-- DoctorPhone: Not Received
AppUser <-- Sharing: Failed to send SMS Message
end


deactivate Sharing
@enduml