@startuml

actor AppUser

create MainActivity
AppUser -> MainActivity: <<create>>
AppUser -> MainActivity: Login Request

activate MainActivity
MainActivity -> MainActivity: File Lookup

activate MainActivity

alt file found
MainActivity <-- MainActivity: Found
create Monitoring
MainActivity -> Monitoring: <<create>>

else file not found
MainActivity <-- MainActivity: Not Found
AppUser <- MainActivity: "Please Register First"
deactivate MainActivity
end

AppUser <-- MainActivity: Login Response
deactivate MainActivity

AppUser -> Monitoring: Connect Request
activate Monitoring

Monitoring -> Monitoring: Turn On Bluetooth
activate Monitoring

alt allow Bluetooth turn on
Monitoring <-- Monitoring: Allow
create ScanActivity
Monitoring -> ScanActivity: <<create>>
Monitoring -> ScanActivity: Connect
activate ScanActivity
ScanActivity -> ScanActivity: Scan
activate ScanActivity
ScanActivity <-- ScanActivity
deactivate ScanActivity
create BLEService
ScanActivity -> BLEService: <<create>>
ScanActivity -> BLEService : Connect
activate BLEService
BLEService -> BLEService: Connect
activate BLEService
BLEService <-- BLEService
deactivate BLEService
ScanActivity <-- BLEService: Connected
deactivate BLEService
Monitoring <-- ScanActivity: Connected
destroy ScanActivity

else deny Bluetooth turn on
Monitoring <-- Monitoring: Deny
AppUser <- Monitoring: "Turn On Bluetooth"
deactivate Monitoring
end

AppUser <-- Monitoring: Connect Response
deactivate Monitoring

AppUser -> Monitoring: Start Monitoring
activate Monitoring
Monitoring -> Monitoring: Monitor PPG and GSR
activate Monitoring
Monitoring -> BLEService: TX Message: "Start"

loop until Stop
activate BLEService
Monitoring <-- BLEService: RX Message: "PPG - GSR"
Monitoring <-- Monitoring: Plot PPG and GSR
alt irregular heart rate
AppUser <- Monitoring: Notification
else
end
AppUser -> Monitoring: Stop Monitoring
Monitoring -> BLEService: TX Message: "Stop"
destroy BLEService
deactivate Monitoring
end

AppUser <-- Monitoring: Monitoring Response
deactivate Monitoring


AppUser -> Monitoring: Share Information
activate Monitoring
create Sharing
Monitoring -> Sharing: <<create>>
destroy Monitoring
activate Sharing
Sharing -> Sharing: Read Information
activate Sharing
Sharing <-- Sharing
deactivate Sharing
AppUser <-- Sharing: Ready
deactivate Sharing

actor Doctor
AppUser -> Sharing: Send SMS
activate Sharing
Sharing -> Doctor: SMS Message
alt success
Sharing <-- Doctor: Received
AppUser <-- Sharing: SMS Message Sent Successfully
else failure
Sharing <-- Doctor: Not Received
AppUser <-- Sharing: Failed to send SMS Message
end


deactivate Sharing

@enduml