@startuml
actor AppUser

AppUser -> Monitoring: Connect Request
activate Monitoring

Monitoring -> Monitoring: Turn On Bluetooth
activate Monitoring

alt allow Bluetooth turn on
Monitoring <-- Monitoring: Allow
create ScanActivity
Monitoring -> ScanActivity: <<create>>
Monitoring -> ScanActivity: Connect
activate ScanActivity
ScanActivity -> ScanActivity: Scan
activate ScanActivity
ScanActivity <-- ScanActivity
deactivate ScanActivity
create BLEService
ScanActivity -> BLEService: <<create>>
ScanActivity -> BLEService : Connect
activate BLEService
BLEService -> BLEService: Connect
activate BLEService
BLEService <-- BLEService
deactivate BLEService
ScanActivity <-- BLEService: Connected
deactivate BLEService
Monitoring <-- ScanActivity: Connected
destroy ScanActivity

else deny Bluetooth turn on
Monitoring <-- Monitoring: Deny
AppUser <- Monitoring: "Turn On Bluetooth"
deactivate Monitoring
end

AppUser <-- Monitoring: Connect Response
deactivate Monitoring
@enduml