@startuml
actor AppUser

create MainActivity
AppUser -> MainActivity: <<create>>
AppUser -> MainActivity: Login Request

activate MainActivity
MainActivity -> MainActivity: File Lookup

activate MainActivity

alt file found
MainActivity <-- MainActivity: Found
create Monitoring
MainActivity -> Monitoring: <<create>>

else file not found
MainActivity <-- MainActivity: Not Found
AppUser <- MainActivity: "Please Register First"
deactivate MainActivity
end

AppUser <-- MainActivity: Login Response
deactivate MainActivity
@enduml