@startuml
actor AppUser

create MainActivity
AppUser -> MainActivity: <<create>>
AppUser -> MainActivity: Register Request

activate MainActivity
create NewUser
MainActivity -> NewUser: <<create>>
destroy MainActivity
alt Sign Up
AppUser -> NewUser: Sign Up(Information)
activate NewUser
NewUser -> NewUser: Write File
activate NewUser
NewUser <-- NewUser
deactivate NewUser

AppUser <-- NewUser: "Registration Successful"
MainActivity <- NewUser: <<create>>
activate MainActivity
deactivate MainActivity

else Cancel
AppUser -> NewUser: Cancel
AppUser <-- NewUser: "Registration Canceled"
MainActivity <- NewUser: <<create>>
activate MainActivity
deactivate MainActivity

destroy NewUser
end
@enduml